---
name: Rapport de projet

on:
  pull_request:
  workflow_dispatch:


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      status: ${{ steps.rapport-changed.outcome }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: docs/rapport.md
      - name: Check if rapport.md changed
        id: rapport-changed
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "No changes in docs/rapport.md. Quitting..."
          exit 1

  generate-rapport:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.status != 'failure'
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install markdown-toc
        run: npm install --save -g markdown-toc
      - name: Run markdown-toc
        run: markdown-toc -i docs/rapport.md
      - name: Generate PDF
        run: docker run --rm --volume "$(pwd)/docs:/data" pandoc/latex rapport.md -o rapport.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate up-to-date rapport.pdf
